Update lint.yml

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -1,4 +1,5 @@
 name: Prettier Code Formatting
+
 on:
   push:
     branches:
@@ -18,10 +19,9 @@ jobs:
 
       - name: Run prettier
         run: |
-          npx prettier --check .
-          if [[ $? -ne 0 ]]; then
-            echo "Prettier found some formatting issues. Please fix them before pushing."
-            echo "To fix the issues, run the following command:"
-            echo "npx prettier --write .`
+          npx prettier --write .
+          prettier_exit_code=$?
+          if [ $prettier_exit_code -ne 0 ]; then
+            echo "Prettier check failed. Please run 'npx prettier --write .' to fix formatting issues."
             exit 1
           fi
